theme: jekyll-theme-hacker
# title: MARTIAN AI
# description: Learn AI for your future
show_downloads: false
show_github_repository: false
# github:
#   repository_url: https://martianvenusian.github.io
